### ISSUE TITLE
How to create new exercises?

### ISSUE THREAD

**Issue by afita** [oliexdev/openWorkout#4] opened 2020-10-19 12:37 UTC
Hello. How can I create new exercises? I created a new Workout, then in the date I added a new workout item, But I could select only from the existing workout items. I would like to create new workout items, with my own videos / images. I tried adding the workout item name "<New workout item>", but I can not change the video (I tried clicking on it, but nothing happened).

I'm using openWorkout version 1.2 from F-droid.

**Comment by jorgman1** [comment] 2020-10-20 10:52
I am able to add a video from the memory card.
However, it might be helpful, if you explain how you created the videos (e.g. in the Readme)

**Comment by AlanSanchezP** [comment] 2020-10-20 16:08
I think that creating new exercises is a bit confusing and it would be great to have a dedicated section to see and edit them all in the app menu

**Comment by afita** [comment] 2020-10-20 17:56
Hi guys. I would appreciate if you could describe how you create new exercises. It seems that you can do it. I really can't figure it out. Thanks.

**Comment by AlanSanchezP** [comment] 2020-10-20 18:14
@afita
Go to Trainings and select any of them, then select any day so that you see the exercises for that day. Then tap the "+" button in the appbar and select "<New workout item>"

**Comment by afita** [comment] 2020-10-20 18:24
Yes, this is how I create training plans.But how do I create new workout items? Whis is what I mean by "exercises": workout items.

**Comment by afita** [comment] 2020-10-21 06:04
Yes, this is what I did: I used "New workout item". But I can not set a new image/video in it. I clicked, I swiped, and nothing happens. The video / image remains with the character staying still.

**Comment by oliexdev** [comment] 2020-10-21 15:01
I thought it were clear with the "+" button which is avialable for the training/days/workouts!?

@afita Did you grant access to the storage device on your smartphone? 
Could you enable the debug log file in the settings and attach the debug log file here?

**Comment by afita** [comment] 2020-10-21 16:22
I'm using the "+" button, it's working and it's obvious what it's for and how to use it.

Here is the Debug log file: openWorkout_2020-10-21_19-08.txt:

[openWorkout_2020-10-21_19-08.txt](https://github.com/oliexdev/openWorkout/files/5417334/openWorkout_2020-10-21_19-08.txt)

I'm also attaching a screenshot to better show what I'm looking for:

![Screenshot_2020-10-21-19-15-08](https://user-images.githubusercontent.com/294730/96748821-bbd09100-13d2-11eb-943b-05649d119a7a.png)

**Comment by oliexdev** [comment] 2020-10-21 17:10
Unfortunately, I can't reproduce it here. I guess if you click on the video no file dialog is opened? Could you enable the debug log and click again on the video? Please attach this result.
Could you uninstall and install openWorkout again? If you click the first time on the video a permission dialog should popup? Did you see that dialog?

**Comment by afita** [comment] 2020-10-21 18:25
The app has the "Storage" permission active. I checked in Settings -> Apps. I can change the icon of the "New workout item" with an image from the Storage (Local & SD Card), so it works.

I reinstalled, after clearing all data first.

When I clicked on the video, nothing happens.

When I clicked on the icon of the workout, the dialog to grant the Storage permission appeared and I granted it, then I could select the image for the icon.

Now I received an OutOfMemory error after I rotated back-and-forth with Auto-rotate active on the phone:

`Build version: 1.2 
Build date: 1980-01-01 00:00:00 
Current date: 2020-10-21 21:17:15 
Device: HUAWEI MYA-L41 
 
Stack trace:  
java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 8388448 free bytes and 13MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:735)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:711)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:530)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1089)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1055)
	at android.graphics.drawable.Drawable.createFromStream(Drawable.java:1041)
	at android.widget.ImageView.resolveUri(ImageView.java:835)
	at android.widget.ImageView.setImageURI(ImageView.java:451)
	at b.b.q.n.setImageURI()
	at com.health.openworkout.gui.workout.WorkoutSettingsFragment.a(:2)
	at com.health.openworkout.gui.workout.WorkoutSettingsFragment.a(:11)
	at androidx.fragment.app.Fragment.b()
	at b.l.d.q.a(:84)
	at b.l.d.q.l(:1)
	at b.l.d.q.a()
	at b.l.d.q.a()
	at b.l.d.q.a(:87)
	at b.l.d.q.l(:1)
	at b.l.d.q.a()
	at b.l.d.q.a()
	at b.l.d.d.onStart(:2)
	at b.b.k.j.onStart()
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6464)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2595)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4407)
	at android.app.ActivityThread.access$1000(ActivityThread.java:196)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:5982)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
`
Here's the debug log after trying to click on the video in order to change it (the previous log was also done after trying to click on the video):  [openWorkout_2020-10-21_21-19.txt](https://github.com/oliexdev/openWorkout/files/5418039/openWorkout_2020-10-21_21-19.txt).

**Comment by oliexdev** [comment] 2020-10-22 16:00
thanks the video file click problem should be fixed now. It was a problem with the old SDK version 23. I implemented a workaround.

**Closed by oliexdev** 2020-10-22 16:00 UTC

**Comment by afita** [comment] 2020-10-22 18:52
Thanks! I am eagerly awaiting for the next version!
